name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo "YOUR_API_KEY=${{ secrets.YOUR_API_KEY }}" >> .env

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          cache: false

      - name: Build Web
        run: |
          flutter clean
          flutter pub upgrade
          flutter config --enable-web
          flutter pub get
          flutter build web --release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web